services:
  postgres:
    image: postgres:16
    container_name: acid_postgres
    environment:
      POSTGRES_USER: acid_user
      POSTGRES_PASSWORD: acid_pass
      POSTGRES_DB: acid_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U acid_user -d acid_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
